import raw from "./Hero.module.css";

export type HeroStyles = {
  readonly hero: string;
  readonly bg: string;
  readonly bgImg: string;
  readonly scrim: string;
  readonly decor: string;
  readonly decorLine1: string;
  readonly decorLine2: string;
  readonly ellipseLarge: string;
  readonly ellipseSmall: string;
  readonly groupWrap: string;
  readonly inner: string;
  readonly header: string;
  readonly nav: string;
  readonly navLogoLink: string;
  readonly navLogo: string;
  readonly navLinks: string;
  readonly navLink: string;
  readonly navCta: string;
  readonly navCtaIcon: string;
  readonly navCtaLabel: string;
  readonly main: string;
  readonly column: string;
  readonly badge: string;
  readonly badgeDot: string;
  readonly badgeText: string;
  readonly stack: string;
  readonly textBlock: string;
  readonly headlineGroup: string;
  readonly hLine1: string;
  readonly hLine2: string;
  readonly subtext: string;
  readonly ctaRow: string;
  readonly btnPrimary: string;
  readonly btnPrimaryIcon: string;
  readonly btnPrimaryLabel: string;
  readonly btnSecondary: string;
  readonly starSvg: string;
  readonly btnSecondaryLabel: string;
  readonly sliderSection: string;
  readonly sliderMask: string;
  readonly sliderTrack: string;
  readonly sliderSet: string;
  readonly sliderLogoWrap: string;
  readonly sliderLogo: string;
};

export const styles: HeroStyles = raw as HeroStyles;
