#!/usr/bin/env node
/**
 * Fetches S&P 500 monthly close prices from Yahoo Finance
 * and generates sp500-data.ts for the Performance component.
 *
 * Usage: node scripts/fetch-sp500.mjs
 *
 * Requires Node 18+ (built-in fetch).
 * Aligns benchmark to Capitalife start date (Apr 2024).
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

const TICKER = "%5EGSPC";
const START_UNIX = Math.floor(new Date("2024-03-01").getTime() / 1000);
const END_UNIX = Math.floor(new Date("2026-04-30").getTime() / 1000);

const CAPITALIFE_LABELS = [
  "Apr 24","May 24","Jun 24","Jul 24","Aug 24","Sep 24","Oct 24","Nov 24","Dec 24",
  "Jan 25","Feb 25","Mar 25","Apr 25","May 25","Jun 25","Jul 25","Aug 25","Sep 25",
  "Oct 25","Nov 25","Dec 25","Jan 26","Feb 26","Mar 26",
];

async function fetchYahoo() {
  const url =
    `https://query2.finance.yahoo.com/v8/finance/chart/${TICKER}` +
    `?period1=${START_UNIX}&period2=${END_UNIX}&interval=1mo`;

  const res = await fetch(url, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    },
  });

  if (!res.ok) throw new Error(`Yahoo API returned ${res.status}`);

  const json = await res.json();
  const result = json.chart.result[0];
  const timestamps = result.timestamp;
  const closes = result.indicators.quote[0].close;

  const baseline = closes[0];
  const points = [];

  for (let i = 1; i < timestamps.length; i++) {
    if (closes[i] == null) continue;
    const date = new Date(timestamps[i] * 1000);
    const label =
      date.toLocaleString("en", { month: "short" }) +
      " " +
      String(date.getFullYear()).slice(2);
    const cumReturn = Math.round(((closes[i] / baseline - 1) * 100) * 100) / 100;
    points.push({ label, cumReturn });
  }

  return points;
}

function alignToCapitalife(points) {
  return CAPITALIFE_LABELS.map((lbl) => {
    const match = points.find((p) => p.label === lbl);
    return match ? match.cumReturn : null;
  }).filter((v) => v !== null);
}

function generateTS(data) {
  return `// Auto-generated by scripts/fetch-sp500.mjs — re-run to update
// S&P 500 cumulative returns (%) aligned to Capitalife start (Apr 2024)
export const SP500_CUM: number[] = [\n  ${data.join(",\n  ")}\n];\n`;
}

async function main() {
  console.log("Fetching S&P 500 monthly data from Yahoo Finance…");

  let data;
  try {
    const raw = await fetchYahoo();
    console.log(`Fetched ${raw.length} monthly points.`);
    data = alignToCapitalife(raw);
    console.log(`Aligned ${data.length} points to Capitalife timeline.`);
  } catch (err) {
    console.warn("Yahoo Finance fetch failed:", err.message);
    console.log("Using fallback data (real S&P 500 approximation).");
    data = null;
  }

  if (!data || data.length < 20) {
    console.log("Insufficient fetched data — writing fallback.");
    data = [
      -4.16, 0.44, 3.92, 5.10, 7.50, 9.67, 8.58, 14.81, 11.95,
      14.96, 11.44, 6.81, 3.16, 5.52, 8.01, 10.24, 8.87, 7.53,
      10.39, 13.25, 15.15, 16.49, 13.82, 16.10,
    ];
  }

  const out = join(process.cwd(), "components", "Performance", "sp500-data.ts");
  writeFileSync(out, generateTS(data));
  console.log(`\n✓ Written ${data.length} points to ${out}`);
  console.log("Final value:", data[data.length - 1] + "%");
}

main();
