// Auto-generated by scripts/fetch-sp500.mjs — re-run to update
// S&P 500 cumulative returns (%) aligned to Capitalife start (Apr 2024)
export const SP500_CUM: number[] = [
  -4.16,
  0.44,
  3.92,
  5.1,
  7.5,
  9.67,
  8.59,
  14.81,
  11.94,
  14.96,
  13.33,
  6.8,
  5.99,
  12.51,
  18.09,
  20.65,
  22.95,
  27.29,
  30.18,
  30.35,
  30.28,
  32.06,
  30.92,
  24.25
];
